[package]
name = "snax"
version = "0.1.0"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
edition = "2018"

[dependencies]
proc-macro-hack = "0.5"
snax_macros = { path = "../snax_macros" }
htmlescape = "0.3.1"
